services:
- type: web
  name: minio
  healthCheckPath: /minio/health/live
  env: docker
  region: frankfurt
  plan: free
  dockerfilePath: ./Dockerfile
  dockerContext: .
  autoDeploy: false
  envVars:
  - key: TAILSCALE_AUTHKEY
    sync: false
  - key: MINIO_ROOT_USER
    generateValue: true
  - key: MINIO_ROOT_PASSWORD
    generateValue: true
  - key: PORT
    value: 10000
